name: Daily Gita Email

on:
  schedule:
    - cron: '0 2 * * *' # Runs at 8 AM IST (2:00 UTC)
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run email script
        env:
          BHAGAVAD_GITA_API_BASE: ${{ secrets.BHAGAVAD_GITA_API_BASE }}
          BHAGAVAD_GITA_API_KEY: ${{ secrets.BHAGAVAD_GITA_API_KEY }}
          BHAGAVAD_GITA_API_HOST: ${{ secrets.BHAGAVAD_GITA_API_HOST }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: python agent.py
